# Generated by Django 4.2.15 on 2024-08-13 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tecnology',
            new_name='technology',
        ),
    ]
