# Generated by Django 4.2.15 on 2024-08-13 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_tecnology_project_technology'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
